### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by KristjanESPERANTO** [yedidiaklein/MMM-whoshome#3]
It would be nice if you would add a license file. MagicMirror and most other modules use the MIT license, here is an example: <https://github.com/MagicMirrorOrg/MagicMirror/blob/master/LICENSE.md> :slightly_smiling_face: 

By the way: Without a license your module can't be displayed with a screenshot on [the new module list](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/) I'm working on.

**Comment by yedidiaklein** [comment]
Hi, 
Tnx !

Added a license file.

**Comment by KristjanESPERANTO** [comment]
Nice! But please enter your name or nickname into the file 🙂

**Comment by yedidiaklein** [comment]
you are right... fixed...

**Comment by KristjanESPERANTO** [comment]
Thanks! Now the new module list shows the screenshot of your module :partying_face:
